= IT business în Moldova și banii în plic

Sunt multe companii offshore IT în Moldova care folosește forța de
muncă ieftină și mințile agere de la noi. Însă aceste companii nu
doresc să plătească impozite statului nostru, așa că unele preferă să
trimată banii în plic pentru angajații săi.

Un îndemn pentru toți colegii de breaslă: nu primiți banii în plic!
Voi veți plăti impozitele pe venit în orice caz dacă vă apucă fiscul
de fund și întreabă de unde aveți mașină, casă, alte bunuri
scumpe. CCCEC a început corect cu Oleg Voronin după zicala că peștele
de la cap se strică, dar peste cât va timp va veni și vremea
noastră. Luând banii în plic, voi secătuiți bugetul statului cu 30%
sau mai mult din salariul ce-l primiți, acești bani trebuie să-i
plătească firma străină și ei sunt necesari statului nostru pentru a
plăti medicii, învățătorii, pentru a ne face drumurile mai bune,
pentru pensiile părinților și buneilor noștri, pentru o viață mai bună
la noi în țară în sfârșit.

Rog să creem o companie de informare și educare a cetățenilor: de
monitorizat companiile locale de IT.

Sunt careva întrebări pentru fisc:

* Vreau să achit impozitele, dar doresc singur să decid la ce
instituții de stat să dau banii.
* O companie străină care nu are oficiu în Moldova, dar are 5-8
angajați care lucrează de acasă, ce impozite trebuie să plătească?
