= 13 lucruri simple care îți pot simplifica ziua de muncă

_”Fă lucrurile dificile atunci când sunt simple și lucrurile mărețe atunci când sunt nesemnificative. O călătorie de mii de mile trebuie începută cu un singur pas.” - Lao Tzu._

Articol scris de link:http://zenhabits.net/2010/03/simplify-your-workday/[Leo Babauta].

Unul dintre cele mai bune lucruri pe care le-am făcut atunci când am
decis să îmi simplific viața a fost să îmi simplific ziua de muncă -
mai întâi la locul permanent de mună și după aceea prin demisia de la
locul permanent de muncă în favoarea a ceea ce fac acum ca scriitor și
antreprenor.

Am eliminat o mare parte din rutină, sarcini
administrative și plictisitoare cu câteva principii simple.

În prezent am eliminat totul ce nu are importanță, astfel că mă pot concentra pe ceea ce îmi place cu adevărat: să creez.

Nu toată lumea poate să facă schimbări atât de drastice spre
simplicitate, dar dacă aveți puțin control asupra zilei dvs de muncă,
puteți face mici modificări care vor simplifica enorm lucrurile.

Dacă nu aveți control sau dacă vă gândiți ”Eu nu pot să fac aceste lucruri”, v-aș întreba: de ce nu? E posibil să schimbi ceva, dacă nu acum atunci pe termen lung? Eu am crezut că ulele lucruri nu sunt posibile (de exemplu să muncești de acasă) care pe termen lung s-au dovedit a fi realizabile.

Nu trebuie să faceți toate aceste lucruri - alegeți doar unul și
încercați-l. Apoi alege încă unul și vezi dacă
funcționează. Experimentați și găsiți ceea ce vi se potrivește.

Și bucurați-vă de viața profesională simplă.

1. *Începe devreme.* Trucul meu preferat era să merg devreme la servici. Înainte să înceapă ședințele și telefoanele să sune era liniște și atunci puteam să muncesc în liniște. Înainte ca toți ceilalți să înceapă munca eu îndeplineam două sau trei sarcini importante.
2. *Limiteaza-ți orele.* Este paradoxal, foarte mulți oameni muncesc multe ore și cred că în acest fel reușesc să realizeze multe lucruri și devin mai productivi, dar ei consumă orele brute pentru probleme. În schimb, limitați-vă orele de muncă - să zicem 6 sau 7 ore pe zi - și încercați să îndepliniți sarcinile esențiale în această limită de timp. Dacă veți ști că puteți lucra doar 6 ore pe zi, vă veți asigura că îndepliniți cele mai importante sarcini la început și veți pierde mai puțin timp. Limitările vă vor forța să fiți eficienți.
3. *Faceți o listă scurtă.* Faceți o listă lungă de sarcini de îndeplinit ... apoi faceți o listă scurtă care conține 1-3 sarcini pe care doriți cu adevărat să le îndepliniți. Alegeți în așa fel încât dacă ați realiza numai aceste sarcini veți fi mândru de ceea ce ați realizat în ziua respectivă. Începeți cu cele mai importante sarcini, înainte de a verifica emailul sau a citi online.
4. *Grupați distracțiile.* Care sunt distracțiile dvs? Probabil lucrurile ca emailul, răsfoirea blogurilor, Twitter sau a altor rețele sociale? Alocați timp pentru aceste activități, de preferat spre sfârșitul zilei: să zicem de la ora 15-16. Nu vă ocupați cu distractiile înainte de orele stabilite. Grupând toate distracțiile în aceeași perioadă de timp, vă dă posibilitatea să vă realizați sarcinile mai întâi, dar aveți programat și timp pentru distracții. O altă abordare este să alocați pentru aceste distracții câte 10 minute la sfârșitul fiecărei ore - dar respectați limita de 10 minute!
5. *Scrieți emailuri mai scurte.* Daca corespondența ocupă o mare parte din zi, atunci o limitare de 3-4 propoziții pentru fiecare email va fi o modificare semnificativă. Mai întâi, acest lucru va micsora semnificativ timpul consumat pentru scrisul și răspunsul la emailuri. În al doilea rând, acest lucru va scurta răspunsul către emailurile dvs, ceea ce înseamnă că veți consuma mai puțin timp citind emailuri.
6. *Limitați ședințele.* Cu cât mai puține, cu atât mai bine. Unii directori de la Google fac ședințe de doar 5 minute - toți care participă la aceste ședințe trebuie sp fie pregătiți și conciși. Dacă reușiți să  evitați prezența la ședințe obținând doar notoțe de la ele sau să găsiți metode alternative de comunicare, acest lucru vă va economisi ore întregi pe săptămână.
7. *Automatizați.* Cu cât veți avea de făcut mai puține sarcini repetitive și de rutină, cu atăt mai mult timp liber veți avea pentru sarcini importante. Automatizați tot ce puteți: încurajații pe oameni să completeze câmpurile electronic, să obțină informații de pe site-ul dvs în loc să va contacteze telefonic sau prin email, folosiți un serviciu automat de procesare a plăților și de expediere a produselor etc.
8. *Eliminați hârtiile.* Eu am lucrat foarte mult cu hârtiile și chiar și atunci știam că aceasta este o mare pierdere de timp. Dacă companiile și organizațiile ar putea înlocui documentele de hârtie în cele în format electronic, aceasta ar economisi multă hârtie și ar reduce efortul de copiere, completare, dublicare. Aceasta poate fi o măsură pe termen lung.
9. *Eliberați-vă masa de lucru.* Acest lucru poate fi făcut în câteva minute. Eliberați cu totul masa de lucru. Lăsați numai câteva obiecte esențiale. Orice altceva trebuie: completat, transmis persoanei corespunzătoare, găsit un loc permanent într-un sertar, distrus/reciclat. Luați decizii rapid și întoarceți-vă la muncă.
10. *Plecați.* Dacă puteți pleca din birou, veți putea găsi un loc liniștit unde vă veți putea concentra pe lucrurile importante. Găsiți un loc unde puteți lucra, deconectați internetul și lucrați, după care conectați-vă iar la internet ca să puteți trimite sau încărca ceea la ce ați lucrat. O bună opțiune este să munciți de acasă. Cu cât mai mult faceți acest lucru (poate fi o dată pe săptămână, o oră, o jumătate din ziua de muncă, o zi de muncă), cu atât mai bine.
11. *Luați pauze.* La fiecare 15-20 de minute ridicați-vă de la masă și luați o pauză. Puteți pur și simplu să vă plimbați prin birou, să salutați pe cineva sau cel mai bine să mergeți afară pentru a lua o gură de aer curat. Plibați-vă un pic, puneți sângele în mișcare, masați gâtul și umerii dacă sunteți tensionați. Faceți flotări dacă vreți să fiți în formă. Când vă întoarceți la muncă, reamintițivă la ce vreți să lucrați și detașați-vă de tot ce vă poate distrage.
12. *Exersați ritualul de atenție.* După fiecare oră sau două ore faceți un ritual de atenție. Aceasta vă va lua doar un minut sau două. Puteți începe prin a închide browser-ul dvs sau alte aplicații, plimbați-vă câteva minute pentru a vă limpezi gândurile și a pune sângele în mișcare. După aceea, întoarceți-vă la cele mai importante sarcini pe care le aveți de făcut și hotărâți ce aveți de făcut în continuare. Înainte să verificcați iar emailul sau să intrați online, lucrați la acea sarcină importantă atât de mult cât puteți. Repetați ritualul de atenție pe parcursul zilei pentru a vă concentra. De asemenea puteţi inspira şi expira adânc pentru a vă readuce în prezent.
13. *Planificați perioade mari de timp pentru a creea.* Nu toată lumea poate să facă acest lucru, dar dacă aveţi această posibilitate, programaţi o perioadă de 3-4 ore pentru creaţie sau alte sarcini importante. Faceţi această perioadă de timp rigidă şi nu permiteţi programarea şedinţelor sau a altor lucruri în această perioadă. Nu planificaţi distracţii in această perioadă, doar faceţi munca care vă place. Dacă este necesar luaţi pauze mici pentru a lua o gură de aer. Bucuraţi-vă de creaţia dvs.
