= Ce importă acum
Traducere: la cartea lui Seth Godin.

== Generozitatea

Cînd economia crește, este firesc să te gândești la tine mai întâi. Ai
o familie de hrănit, un credit ipotecar de plătit. A primi mai mult
pare a fi rânduiala afacerilor.

Se pare că economia conectată nu respectă acest instinct natural. În
schimb, noi suntem recompensați pentru a fi generoși. Generoși cu
timpul şi banii noștri, dar cel mai important: generoți cu arta noastră.

Dacă faci o diferenţă(dezechilibru), oamenii vor gravita la tine. Ei doresc să
se te angajeze, să interacţioneze şi să te implice mai mult.

Dacă faci o diferenţă, de asemenea faci o conexiune. Tu interacționezi
cu oameni care doresc să fie interacţionați şi faceţi modificări pe
care oamenii le respecte și tânjesc după ele. Arta nu se poate
întâmpla fără ca cineva care încearcă să facă o diferenţă. Aceasta
este arta ta, este ceea ce faci. Atinge oameni sau proiecte şi
schimbaţi spre mai bine. În acest an, veţi găsi cu siguranţă că cu cât mai  mult dai, cu atât
mai mult primești.

== Teama

V-aţi întrebat vreodată cine e în spatele acestei voci mici în capul
tău care iți spune, ”vă aflaţi în această situație de unul singur, o
persoană nu face o diferenţă, aşa că de ce să mai încerci?)

Numele acestei voci este Frica. Frica joacă rolul de antagonist în povestea vieții tale. Trebuie să scapi de ea, folosind toate mijloacele disponibile.

Suntem impresionaţi de multe ori de către cei care par a fi fără
frică: oameni care zboară pe Lună, voluntari în zone
periculoase de război, care vorbesc în fața a mii de oameni, care se
confruntăcu cancerul, care strâng bani ca să adopte un copil care nu
este din carnea lor şi de sânge.

Deci, de ce suntem atât de inspirați de ei?

Noi toţi împărtăşesc aceleaşi caracteristici ca și cei curajoși.

Suntem toţi în sfârșit oameni.

Până cînd Frica va pleca, (şi-ți dai seama că nu poate pleca pe totdeauna)
i-a o decizie de a fi curajos. Lumea are nevoie de povestea ta pentru
a fi completă.

== Fapte

TODO: image from page 7

== Demnitatea

Demnitatea este mai importantă decât bogăţia. Va fi mult, mult timp
înainte de a putea face toată lumea de pe pamânt bogată, dar putem
ajuta oamenii să găsească demnitatea în acest an (chiar acum, dacă
alegem să ...).

Demnitate provine de la crearea destinului dumneavoastră şi de la
respectul pe care-l primești de la familie, colegii de breaslă şi
societate.

Un fermier în măsură să hrănească familia sa şisă  câştige suficient
pentru a trimite copiii la școală a câştigat respectul oamenilor din
satul lui - şi mai important, o conexiune la restul dintre noi.

Este uşor să-l lipsești de demnitate pe cineva, dar dificil de a o da
înapoi. Ultimii ani ne-au învăţat cât de conectată este întreaga lume
- o prostituată în cartierele sărace din Nairobi este doar o figură
importantă în viaţa ta ca un poştaş în următorul oraş. Şi într-o lume
în care totul este conectat, cel mai important lucru ce putem face
este să tratăm semenii noştri cu demnitate.

Oferirea de un produs alimentar sau bani unei persoane sărace, l-ar putea
ajuta să supravieţuiască o altă zi... dar nu-i dai demnitate. Există
o cale mai bună.

Crearea posibilităților pentru oameni de a rezolva propriile probleme, nu
este doar o ocazie în 2010. Este o obligaţie.

== Sensul

TODO: imaginea din pagina 10

== Liniștea

Noi suntem ”strivingest” oameni care au trăit vreodată. Suntem
ambiţioși, înfometați de timp, competitivi, zăpăciți. Noi ne mișcăm cu
viteză maximă, dar în mod constant ne temem că nu facem
suficient. Deşi trăim mai mult decât orice oameni din înaintea noastră,
vieţile noastre se simt mai scurte, mai agitate, fără răsuflare...

Dragilor, liniștiți-vă. Apăsați frânele. Făceți un înapoi. Serios. Faceți doi
paşi înapoi. Opriţi toate electrocasnicele dumneavoastră şi predați-vă asupra
tuturor aspiraţiilor dumneavoastră şi nu faceți absolut nimic într-un
interval de timp. Ştiu, ştiu - Cu toţii avem nevoie să salvăm lumea.
Dar ai încredere în mine: lumea va avea nevoie și mâine să fie salvată. Între timp, vei avea un accident vascular
cerebral în curând (sau cauza un accident vascular cerebral în
altcineva), dacă nu vă calmați dracului.

Deci, du-te și fă o plimbare. Sau nu. Expirați. Găsiţi un bazin de apă
şi plutiți. Bateți o minge de tenis de un perete. Spune-ți colegilor dumneavoastră că sunteţi
în meditație (meditaţia oamenii o iau în serios, așa că veți fi
scutiți de explicații adăugătoare) şi apoi de fapt, în secret, trageți
un pui de somn.

Sugestia mea radicală? Încetaţi să participați, numai
pentru o zi din acest an - în cazul în care numai pentru a vă asigura
că nu ați pierdut pentru totdeauna rarul şi dispărutul talent omenesc de a
aprecia liniștea.

De Elizabeth Gilbert.

== Conectați

Exista zeci de mii de întreprinderi care fac multe milioane pe an de
profit, care încă nu au auzit vreodată de twitter, bloguri sau
Facebook. Sunt toate pe cale greşită? Au pierdut sau este într-adevăr
o glumă pe noi? Ei fac afaceri prin intermediul unei relații
personale, prin livrarea de servicii eminente clienților și aceasta lucrează
pentru ei. Sunt mai de succes decât majoritatea acelor firme care
pierd ore pontificând despre modul în care ceilalţi pierd din
lipsa lor în mass-media sociale şi ultimul val. Şi totuşi, ei fac
afaceri. Foarte bune afaceri. Nu scrie despre asta. Fă-o.

Sunt uimit continuu de numărul de oameni pe Twitter şi pe blog-uri,
precum şi creşterea de oameni (şi branduri) pe Facebook. Dar m-a
uimit, de asemenea, și modul în care atât de mulţi dintre noi petrec
timpul. Camera de ecou pe care o construim devine din ce în mai mare şi mai tare.
Mail multe megafoane nu este egal cu un dialog mai bun. Am devenit
sclavii dispozitivelor noastre mobile şi strălucirii ecranelor
noastre.

Mergem pe străzi cu capul în jos uitîndu-ne în ecrane de 3 inci, în
timp ce lumea se mișcă iute și face acelaşi lucru. Şi totuşi, suntem
convinşi că suntem mai conectați între noi decât oricând
înainte. Multi-tasking a devenit o insigna de onoare. Vreau să ştiu de
ce.

Eu nu am toate răspunsurile la aceste întrebări, dar eu personal
gândesc la ele mai mult şi mai mult. Printre tweets, blog posturi şi
actualizări Facebook.

_De Howard Mann_.

= Re-Capitalismul

”Marx a citit Darwinul său, dar el a luat-o greşit - capitalismul nu se
autodistruge, se adaptează.” --Tom Stoppard

*Capitalismul nu este imutabil* - s-a schimbat înainte (amintește-ți
de industrializare?) și va face-o din nou.

Darwin a scris despre cintezele din insulele Galapagos, observând că
forma ciocurilor la fiecare populaţiei este asemenea la forma florilor
ce le servește ca hrană. Gândiţi-vă la afaceri ca indivizi din specia capitalistă. Formele de companii vor evolua cu modificările lumei din jurul lor.

Ce s-a schimbat? În primul rând: creşterea globală nu va mai veni din
partea economiilor cu venit ridicat (pe care le consumă 77% din PIB-ul
lumii de azi - doar 32% până în 2050.) Al doilea rând, la fel cum
tehnologia industrială a format societate Statelor Unite în secolul
XX, tehnologia informaţională va fi în funcţie de curs de dezvoltare
"nativ digitală" a economiei din XX. Ca cintezele, întreprinderile vor
schimba formele lor de a face supravețuirea lor în acest nou mediu cu
venituri reduse, creşteri rapide, conectat la nivel global, de
informare intensivă.

Cum? Ei vor învăţa să puie prețurile și să facă publicitate la mărfuri
al căror cost marginal este zero. Ei vor învăţa să profite din împărțirea
valorilor. Ei vor prefera colaborarea în schimbul concurenţei. Ei îşi
va asuma responsabilitatea pentru nou-măsurabile "externe", pe care le
impun societăţilor lor.

Dacă locuiţi sau operați într-o lume dezvoltată, ai o problema - ai o
mulţime de a dezvăţa, şi nu pe termen scurt stimulent pentru a
face-o. Dar mai bine nu trebuie de ignorat un concurent cu un straniu
cioc.

== Viziunea

Viziunea este seva în orice organizaţie. Aceasta este ceea ce o
menţine să progreseze. Aceasta prevede la sensul de zi cu zi şi provocările obstacole care alcătuiesc (rumble) şi (tumble) din viața reală.

Într-o economie de jos-în special cel care a luat cele mai multe dintre noi prin surprindere-lucrurile devin foarte tactic. Incercam doar pentru a supravieţui. Ceea ce a lucrat ieri, nu neapărat de lucru azi. Ceea ce lucrări de azi poate să nu neapărat de lucru mâine. Deciziile devin pragmatice.

Dar, după un timp acesta poartă pe oameni. Ei nu ştiu de ce eforturile
lor importă. Ei nu pot conecta acţiunile lor la o poveste mai
mare. Munca lor devine o chestiune doar de trecerea, trăind de la
sfârşit de săptămână la sfârşit de săptămână, de la salariul la salariul.

Aici este și cazul în care o bună conducere face o mare
diferență. Leadership-ul este mai mult decât o influenţă. Ea este
despre amintind oamenilor de ceea ce încercă să construiască și de ce
este important. Este pictura despre o imagine a unui viitor mai
bun. Ar fi la fel ca şi zicând: "Hai. Putem face acest lucru!"

Atunci când sunt timpuri grele, viziunea este prima care e
vinovată. Înainte de îmbunătățirea condiţiilor, viziunea este primul
lucru pe care trebuie recuperat.

_de Michael Hyatt_

== Îmbogățirea

Suntem toţi într-o căutare - o căutare de mai mult sens în viaţa
noastră.

Prin alegerea de a îmbogati viața altor persoane, adăugaţi sens atât
vieţilor lor cât şi vieții dumneavoastră.

Unii paşi simpli pentru a urma:

1. *Aderarea* la relaţii pe viață ce generează evenimente, companii, cauze şi limite geografice.
2. *Grija* pentru preocupările altora, cum ar fi proprii.
3. *Conectează* pe cei care vor beneficia şi vor îmbogăţi vieţile reciproc, în egală măsură.
4. *Comunicaţi* sincer. Spune oamenilor ceea ce ei ar trebui să audă, decât ceea ce vor să audă.
5. Măriți capacitatea: Obiectiv pentru a extinde capacitatea oamenilor de a le ajuta să dea şi să obţină mai mult de la propriile lor vieţi.

*Testul lui Litmus*: Dacă îmbogăţiți într-adevăr viaţa cuiva, lor le va
fi dor de tine de obicei, în trecutul lor. Ei cred că viaţa lor ar fi
fost chiar mai bină dacă v-ar fi cunoscut mai devreme.

Sunteţi doar atât de bogat, câtă îmbogăţire aduceți lumei din jurul tău.

_de Rajesh Setty_

== 1%

TODO

== Vorbiți

== Atomi

== Excelența
