= Înlocuieşte-te – Un ghid pentru delegarea volumului tău de muncă
Author: Collis Ta'eed
Noiembrie 2009:
Traducere, link:http://thenetsetter.com/blog/startups/replace-yourself-a-guide-to-delegating-your-workload[originalul]

Pentru cei mai mulţi antreprenori, ambiţia depăşeşte cu mult chiar şi o zi de lucru supraomenească. Nu contează pe ce parte o întorci, o persoană nu poate face mai mult. Pentru a face mai mult, este nevoie nu doar de a munci foarte, foarte mult. Este nevoie de delegare.

Nicăieri în lume nu există o copie de a ta, dar există o mulţime de alţi oameni. Aşadar, pentru a depăşi pragul de viteză a capacităţilor tale de muncă, trebuie să îi pui pe alţii să preia unele atribuţii ale tale. Această perspectivă poate fi destul de descurajantă, pâna la urmă cum îi găseşti pe aceşti oameni? Cum să ai încredere că o să îndeplinească sarcinile bine? Cum să îi plăteşti? Ce se întâmplă dacă ei nu se descurcă?

De fapt, acest pas este atât de înspăimântător încât, de multe ori, pare mult mai uşor să continui să îţi faci munca singur. Eu personal de multe ori îmi maschezi grijile cu pretexte care par destul de justificate, cum ar fi: „Numai eu am acele aptitudini extraordinare pentru a îndeplini această sarcină” sau „până învăţ pe cineva cum se face, la fel de bine pot să o fac şi singur!”

Dar am decoperit că dacă vrei să creşti şi să te extinzi şi să realizezi tot ce ţi-ai propus este nevoie să faci compromisuri. Şi de fapt, există cineva care poate să îndeplinească una sau mai multe sarcini pe care le faci tu, de multe ori chiar mai bine decât tine. Da, acea persoană are nevoie de instruire şi de timp pentru asimilare, dar aproape fiecare sarcină se va repeta sau vor exista situaţii similare şi atunci vei fi recompensat.
De-a lungul anilor, am acumulat experienţă în angajarea de personal,
atât angajaţi full-time, cât şi colaboratori pe proiect. Deci am pus
nişte gânduri laolaltă despre cum să te faci înlocuit.

== Stabileşte care sunt punctele tale forte şi încearcă să delegi celelalte responsabilităţi (pentru început).
Pentru majoritatea antreprenorilor, o zi de muncă implică o mare
varietate de sarcini, unele dintre ele solicită aptitudinile tale de
bază, iar unele le faci pentru că nu ai de ales. Fă o listă cu
sarcinile pe care le ai şi sortează-le în funcţie de ce ştii tu să
faci mai bine. Întreabă-te: dacă ar fi să angajez pe cineva pentru
această muncă, m-aş alege pe mine dintr-o mulţimede candidaţi? Există
şanse că tu faci o mulţime de lucruri pe care alţii ar putea să le
facă mult mai bine.

Este important ca atunci când faci acest exerciţiu, să nu te
concentrezi pe anumite informaţii particulare despre afacerea
ta. Aceasta este o capcană. Da, tu poţi fi singura persoană care a
fost acolo din prima zi a afacerii tale şi numai tu ştii ce este în
mintea ta, dar uită despre toate astea. Gândeşte doar din perspectiva
abilităţilor. Ce sarcini ţi se potrivesc? Ce îţi place?

Sarcinile care ţi se potrivesc cel mai mult ar trebui să le delegi în
ultimul rând. Restul încearcă să le grupezi pe tipuri de activităţi
similare. Câteodată este nevoie de agilitate mentală pentru a grupa
nişte activităţi, mai ales dacă acestea nu sunt profesii
propriu-zise. Am constatat că la începutul afacerii noastre, în
general, am avut nevoie de oameni inteligenţi care să fie de folos
într-o multitudine de sarcini. De multe ori acele persoane erau
cofondatorii afacerii mele care aveau bunăvoinţa să facă de toate, de
la a oferi suport şi a modera forum-uri, până la deschiderea
conturilor bancare şi întocmirea rapoartelor financiare. Cu timpul,
atunci când bugetul şi nevoile noastre au crescut, am putut angaja
persoane specializate pentru acele activităţi.

De exemplu, recent am descoperit o serie de posturi care necesită
cunoştinţe juridice. Fie că este vorba de citirea contractelor, sau de
consultarea firmei de avocatură cu privire la marca comercială, sau
pur şi simplu exprimarea opiniei asupra unei probleme ce ţine de
drepturi de autor. În prezent, majoritatea acestor sarcini sunt
îndeplinite de mine sau de alt personal din conducere. În firma
noastră nu există destulă muncă pentru un jurist (slavă Domnului,
pentru că sunt foarte scumpi!), dar este destulă muncă pentru un
angajat prin cumul cu cunoştinţe juridice. Şi foarte important este că
o astfel de persoană, fără îndoială, ar munci mai bine, mai repede şi
mai eficient.

== Fereşte-te de falsele economii.

Un motiv general pentru a nu delega este că pur şi simplu nu îţi
permiţi să plăteşti pe altcineva. De multe ori firmele mici şi cele
noi sunt limitate în resurse, deci este evident să faci totul
singur. În general eu admir această strategie, pe care cu siguranţă am
aplicat-o şi eu în afacerile mele, dar trebuie să ţii minte că făcând
totul de unul singur poţi cădea în capcane.

Show-ul meu preferat de televiziune este unul englez care se numeşte
„Property Ladder” care urmăreşte proiecte mari de dezvoltare conduse
de dezvoltatori imobiliari. De multe ori aceste afaceri sunt la
început, implicit cu buget limitat. Cea mai utilizată metodă de a
economisi bani pe care o aleg aceşti oameni este să se ocupe personal
de gestionarea proiectului de dezvoltare. În jumătate din cazuri ei de
fapt pierd bani pentru că nu ştiu de fapt ce fac. Chiar şi cu cele mai
bune intenţii şi cu multă muncă, uneori, ei pur şi simplu fac
lucrurile mai încet sau accidental le fac în ordinea greşită. Când te
uiţi la recapitulare la sfârşitul show-ului realizezi că lucrurile ar
fi decurs mai bine dacă pur şi simplu angajau un profesionist.

O altă falsă economie poate să apară din folosirea necorespunzătoare a
timpului tău. Întreabă-te: Ce aş putea realiza dacă mi-aş elibera
câteva ore? La ce sarcini aş fi cel mai eficient? În multe etape a
dezvoltării lui „Envato” mă pomeneam că fac unele lucruri pentru care
puteam găsi pe cineva să le facă, în acelaşi timp lăsând la o parte
sarcinile pe care nimeni altcineva nu le putea face. Aceasta este că
atunci când foloseşti un tanc pentru a trasporta soldaţii pe câmpul de
luptă, în loc să îl foloseşti la ceea ce este eficient – să arunce
lucruri în aer pe linia de front!

Soluţia este să gestionezi eficient toate resursele tale, inclusiv
timpul ŞI banii. Câteodată aceasta presupune să faci chiar tu unele
lucruri, dar câteodată aceasta presupune delegare.

== Obţine mentalitatea de delegare.

Când eşti foarte ocupat este extrem de dificil să te gândeşti să
angajezi pe cineva. Acest lucru devine de două ori mai dificil atunci
când ai acumulat foarte multă experienţă în anumite situaţii
particulare şi o persoană nouă ar avea nevoie de instruire. Pentru a
depăşi această dificultate trebuie să gândeşti în maniera de delegare.

Pentru început, nu te ataşa de anumite activităţi. Suna aiurea, dar
multe persoane doresc să fie apreciate pentru ceea ce
fac. Preşedintele Harry S. Truman a spus odată: "Este uimitor ce poţi
realiza, dacă nu îţi pasă cine va fi apreciat pentru aceasta". Poate
fi greu să renunţi la nişte activităţi importante şi distractive, dar
în final acest lucru te va ajuta să faci mai mult în ansamblu.

În al doilea rând este important să te pregăteşti pentru un volum mai
mare de muncă pe care îl implică delegarea în fazele
iniţiale. Căutarea şi instruirea personalului necesită mult timp, dar
pentru o perioadă scurtă de timp. După care, dintr-o dată vei avea mai
mult timp liber pentru că te-ai eliberat de unele
responsabilităţi. Trebuie doar să te pregăteşti pentru o explozie a
volumului de muncă pentru o perioadă scurtă de timp şi să aştepţi să
treacă.

== Găseşte oameni ... oriunde!

Am fost întrebat de nenumărate ori unde îi găsim pe acei oameni
minunaţi care lucrează la Envato. Răspunsul este: oriunde şi peste
tot. Aici sunt patru surse principale:

* *Site-uri pentru liber-profesionişti* – De multe ori am delegat sarcini liber-profesioniştilor şi contractorilor. Există o mulţime de site-uri unde poţi posta oferte de muncă pentru freelanseri, dar cel mai bun este FreelanceSwitch’s Job Board unde poţi posta gratuit şi care din coincidenţă este condus de Envato. Sunt foarte mândru să spun că un mare număr de freelanceri i-am găsit acolo! Bineînţeles, tu poţi încerca şi alte site-uri, cum ar fi Elance şi oDesk.
* *Din baza ta de date* – acesta nu se potriveşte tuturor afacerilor, dar în cazul lui Envato noi am găsit foarte mulţi oameni din comunitatea companiei noastre. Majoritatea redactorilor de Tuts au fost cititori şi / sau scriitori pentru site-uri, toţi analiştii pieţelor noastre sunt vânzători în primul rând, în mod similar cu moderatorii, administratorii de site-ul, şi o multime de alte poziţii. De fapt, utilizatorii site-urilor noastre sunt avantajaţi atunci când angajăm pentru că ei nu trebuie să înveţe despre cultură, produs şi companie de la zero.
* *Site-uri de recrutare* – Recent am angajat câteva persoane full-time pentru biroul nostru din Melbourne. Pentru aceasta am postat oferte de muncă pe Seek, care este cel mai mare site de recrutare din Australia. Fiecare ţară are un astfel de site şi este important ca anunţul să fie orientat către piaţă. Odată am postat un anunţ de angajare pentru un programator pe site-ul de recrutare 37Signals şi nu am găsit nici un candidat. S-a dovedit că programatorii australieni nu acordă prea multă atenţie acestui site.
* *Oamenii pe care îi cunoşti* – De când a fost înfiinţat Envato noi am angajat persoane pe care le cunoaştem. De multe ori au fost prieteni sau rude, iar după ce am crescut, au început să fie persoane care au lucrat cu angajaţii noştri la locuri de muncă anterioare. Cunoscând pe cineva sau având o recomandare personală, poţi stabili mai uşor cât de bine se potriveşte o persoană pentru locul de muncă dat, dar trebuie să ţii minte că tu trebuie să alegi persoana potrivită pentru acea muncă, nu pe cineva care întâmplător este disponibil.

La sfârşitul zilei vei putea găsi oameni de aproape oriunde. Doar ţine
ochii deschişi şi asigură-te că oamenii ştiu că eşti în căutare – fie
prin postarea de oferte de muncă, fie prin discuţii cu prietenii.

== Informarea şi instruirea sunt cruciale.

Din păcate, doar să angajezi pe cineva nu este de ajuns. Contractantul
tău, angajatul sau partenerul trebuie să fie pe deplin informat sau
instruit asupra a ceea ce are de făcut. Acesta este un pas crucial
peste care e foarte uşor să î-l omiţi în speranţa deşartă că „î-şi vor
da ei singuri seama”.

Deşi nu este o idee rea să pui oamenii în situaţii dificile, dar
trebuie să te asiguri că ei au totul de ce au nevoie pentru a
munci. De aceea este nevoie de timp pentru instruirea şi formarea
corespunzătoare a acelei persoane. Însă încercarea de a economisi din
aceste costuri implică riscuri foarte mari şi de obicei rezultatele nu
sunt cele mai favorabile. Într-o serie de situaţii am pus pe cineva
semiinformat sau neinstruit pe deplin să îndeplinească o sarcină şi
într-un fel sau altul, întotdeauna am plătit preţul.

Indiferent dacă informezi sau instruieşti, alege o abordare foarte
detaliată. Imaginează-te pe tine în situţia lor, dar cu zero
cunoştinţe despre locul de muncă. Gândeşte-te la toate informaţiile de
care ar putea avea nevoie angajaţii tăi şi documentează-le. O sinteză
completă, specifică şi bine documentată va salva foarte mult timp în
viitor, îi va permite angajatului tău să îşi îndeplinească sarcinile
şi va asigura şi va înlesni tranziţia muncii tale.

== Nu controla totul!

Nu trebuie în nici un caz să încerci să controlezi în detaliu munca
altei persoane. Este foarte descurajant pentru cealaltă persoană şi
este inutil pentru că există două persoane care efectiv fac unul şi
acelaşi lucru.

Există două motive din care tu ai putea să încerci să controlezi o
persoană. Primul motiv este că nu te poţi despărţi de acea activitate
aşa că te-ai hotărât să o verifici tot timpul, să o dirijezi şi
supraveghezi în totalitate. Există o singură soluţie pentru acest
scenariu – renunţă. Nu există o a doua cale, chiar trebuie să renunţi
la acea activitate. Stabileşte verificări la intervale de timp
suficient de lungi încât persoana respectivă să aibă timp să muncească
şi să obţină rezultate. Asta înseamnă că vei supraveghea în continuare
acea activitate, dar o vei face de la o distanţă măsurată. Atunci când
faci verificările, concentrează-te pe rezultate, nu pe modul în care
acestea au fost obţinute. Dacă rezultatele sunt satisfăcătoare, atunci
te poţi relaxa, dacă nu, atunci citeşte al doilea scenariu...

Ai angajat persoana greşită. Ai făcut greşeala să angajezi pe cineva
incapabil să muncească eficient. O ştii şi începi să controlezi acea
persoană în încercarea de a compensa. Îmi pare rău, dar asta nu va
funcţiona. Trebuie să îţi faci curaj, să scapi de acea persoană şi să
o iei de la capăt. Vestea bună este că acest proces este atât de
dureros, încât data viitoare vei alege candidaţii cu mai multă
atenţie!

Ţine minte, nu există nici o situaţie bună care să implice controlul
în detaliu. Dacă eşti pregătit pentru delegarea sarcinilor tale,
trebuie să o faci şi apoi să te retragi ca să te poţi bucura de
beneficii. Dacă nu eşti pregătit pentru delegare este de înţeles, dar
nu te preface că ai delegat şi apoi să controlezi toate
activităţile. Acest lucru pur şi simplu te va costa bani şi nu îţi va
economisi timpul.

== Trebuie să stabileşti aşteptările tale, să ceri responsabilitate şi să oferi feedback.

Fie că este vorba de un freelanser sau de un angajat al firmei, este
foarte important să setezi parametrii de muncă şi să încadrezi
angajatul în acei parametri. Aceasta presupune informarea şi
instruirea pe care le-am menţionat mai devreme, dar şi specificarea
modului în care va fi evaluată performanţa, ce rezultat este bun, ce
rezultat este rău şi cât de des vei oferi feedback-ul. De asemenea,
asta presupune ca tu să urmăreşti şi să apreciezi evoluţia acelei
persoane.

Dacă nu setezi aşteptări şi nu oferi feedback, laşi lucrurile în voia
sorţii. Nimănui nu-i place să lucreze în zadar. Fără aşteptări şi
feedback, angajaţii tăi nu vor putea spune ce au vrut să facă, chiar
dacă o fac şi o fac bine.

Sper ca aceste şapte sfaturi te vor ajuta în misiunea ta de a delega
şi a înlătura o parte din activităţile tale. Chiar şi după toţi acei
oameni pe care i-am angajat, eu încă învăţ despre acest proces. Din
fericire, e destul de amuzant şi atunci când te uiţi înapoi şi vezi ce
a fost realizat fără ca tu să munceşti efectiv, te cuprinde un
sentiment extraordinar.

După ce am scris acest articol lung despre cum şi de ce ar trebui să te faci înlocuit, voi termina cu o poveste moralizatoare. În cartea sa „Povestiri despre Facebook, YouTube şi MySpace”, autorul Sarah Lacy relatează povestea lui Jay Adelson cel care a înfiinţat compania Equinix în timpul boom-ului dot-com. Lacy scrie:

„Ca antreprenori începători, Jay a făcut greşeala de a pierde controlul. În jurul anului 2000, el încă mai era acţionar majoritar la Equinix, dar a renunţat la scaunul său în favoarea proaspătului director executiv „crescut” de companie, Peter Van Camp. Cu toate că Jay şi-a păstrat titlul de cofondator şi de director al departamentului tehnologic, influenţa sa a scăzut considerabil – el nici măcar nu răspundea direct în faţa lui Van Camp.”

Mai târziu, când lucrurile au mers foarte prost şi Adelson era în imposibilitatea de a influenţa cursul evenimentelor, a fost dat afară din compania pe care a creat-o. În timp ce compania există şi acum şi valorează aproximativ 2 miliarde dolari, Adelson printr-o serie de evenimente nefericite, a pierdut totul.
Deci, delegarea şi renunţarea la unele activităţi sunt foarte importante, în acelaşi timp nu vrei să fii exclus din propria afacere pe care ai demarat-o! Cu toate acestea, povestea are un final fericit pentru că la un moment dat, la Equinix, Adelson a întâlnit un tânăr şi înflăcărat inginer pe nume Kevin Rose. Rose şi Adelson au devenit foarte repede prieteni şi cofondatori a unui mic site pe nume Digg. Yay!
